# Site settings
title: Muhammad Faisal
email: your-email@domain.com
url: https://faisalazam.github.io/
description: "A seasoned software engineer's portfolio"
keywords: "Software Engineer, Web Developer, Portfolio, Java, Spring, AWS, Software Development"
skills: "Fearless Architect of High-Impact, Scalable Software Solutions | Champion of Agile Excellence and Modern Development Practices"
meta_author: Faisal Muhammad

# Google webmaster tools
google_verify: "yTthMbVAt2XxKiMbHHs3kwdQbbblfAwB5bfPQwxnaZk"

# Bing webmaster tools verification
bing_verify: "89D0325C86744CAC39F4BE9C28AE8865"

# Contact form:
# - static: pass through formspree.io to validate email sending
# - disqus: replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b27482  # Primary color for your portfolio (you can adjust this to your preference)
  primary-rgb: "24,288,156"  # RGB value for the primary color
  secondary: 2c3e50  # Secondary color
  secondary-dark: 233140  # Darker shade of the secondary color

# Footer settings
footer:
  copyright: Muhammad Faisal
  location: Australia
  social: Around the Web
  credits: "Quick Links"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/muhammadfaisal2
  - title: github
    url: https://github.com/faisalazam
  - title: facebook
    url: https://facebook.com/faisalazam1616
  - title: stack-overflow
    url: https://stackoverflow.com/users/22493607

# Postal address (add as many lines as necessary)
address:
  - line: Sydney
  - line: New South Wales

credits: >
  <ul style="list-style-type: none; padding: 0; margin: 0;">
    <li><a style="color: #fff;" href="#about">About Me</a></li>
    <li><a style="color: #fff;" href="#organisations">Experience</a></li>
    <li><a style="color: #fff;" href="#portfolio">Portfolio</a></li>
    <li><a style="color: #fff;" href="#certifications">Certifications</a></li>
    <li><a style="color: #fff;" href="#faqs">FAQs</a></li>
    <li><a style="color: #fff;" href="#contact">Contact</a></li>
    <li><a style="color: #fff;" href="../assets/docs/Detailed_Resume.docx" download><i class="fa fa-download"></i> Resume</a></li>
  </ul>

# Build settings
markdown: kramdown
permalink: pretty

# For posts (adjust if you need specific post-related settings)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  certifications:
    output: true
    permalink: "/certification/:title/"
  faqs:
    output: true
    permalink: "/faq/:title/"
  organisations:
    output: true
    permalink: "/organisation/:title/"
  testimonials:
    output: true
    permalink: "/testimonial/:title/"
